### ISSUE TITLE
gitlab status error 

### ISSUE THREAD

**Issue by justzx2011** [horizoncd/horizon#115]
One click installation by helm，gitlab can not start for long time:
horizoncd      horizon-gitlab-0                                    0/1     ContainerCreating   0          28m
my k8s version v1.21.14+k3s1
root@horizon-gitlab-0:/# gitlab-ctl  status
run: gitaly: (pid 3916) 195s; run: log: (pid 963) 1567s
run: logrotate: (pid 3941) 194s; run: log: (pid 817) 1592s
run: postgresql: (pid 3972) 194s; run: log: (pid 1178) 1535s
run: redis: (pid 3983) 193s; run: log: (pid 878) 1579s
run: sshd: (pid 3992) 193s; run: log: (pid 108) 1669s

**Comment by justzx2011** [comment]
root@horizon-gitlab-0:/# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3992/qemu-x86_64
tcp        0      0 127.0.0.1:9236          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      3992/qemu-x86_64

**Comment by kilosonc** [comment]
Is there any event about gitlab?

**Comment by justzx2011** [comment]
{"level":"warning","msg":"grpc: addrConn.createTransport failed to connect to {/var/opt/gitlab/gitaly/internal_sockets/ruby.1  \u003cnil\u003e 0 \u003cnil\u003e}. Err: connection error: desc = \"transport: Error while dialing dial unix /var/opt/gitlab/gitaly/internal_sockets/ruby.1: connect: connection refused\". Reconnecting...","pid":943,"system":"system","time":"2023-04-03T04:54:54.226Z"}

2023-04-03_04:55:12.85274 FATAL:  Peer authentication failed for user "gitlab"
2023-04-03_04:55:12.85275 DETAIL:  Connection matched pg_hba.conf line 70: "local   all         all                               peer map=gitlab"
