### ISSUE TITLE
Decoupling of CI/CD

### ISSUE THREAD

**Issue by kilosonc** [horizoncd/horizon#145]
| Event | Description | Status |
| ---- | ---- | ---- |
| Decoupling of CI/CD | Support deploying directly through images without building | Pending |

**Comment by xuzhu-591** [comment]
Design of Image deploy: [image-deploy](https://docs.google.com/document/d/1o7RcmHxSr3pbR1txH3Zhi4jARwJdeeHtIEFq0GOSXH4/edit?usp=sharing)
