### ISSUE TITLE
A bug about the docs

### ISSUE THREAD

**Issue by Acatdef** [horizoncd/horizon#174]
I fount a link about Chinese docs on the websites,but when I choose Chinese ,the language of this page is still English .
Like this https://horizoncd.github.io/zh/docs/user-guide/administrator/idp

Where can I find the really Chinese docs ?

**Comment by kilosonc** [comment]
@Acatdef Sorry, we don't have enough energy to translate the documents into Chinese at the moment, but you could contact us in Slack if you have any question.
