### ISSUE TITLE
Can't log in with nodeport

### ISSUE THREAD

**Issue by noovertime7** [horizoncd/horizon#187]
### Installation Type

script (full)

### Installation Result

success

### Installation Duration

2 ~ 5min

### Environment

```markdown
- OS:Centos8
- CPU:vm
- Memory:8G
```

### Suggestions & Bugs

I used ``helm install horizon horizon/horizon -n horizoncd --version 2.1.4 --create-namespace`` to successfully install the application, but my cluster doesn't have ingress, so I tried to put horizon-web service type to nodePort, the page jumps to /dashboard/clusters after accessing it and I can't log in, it doesn't work
![image](https://github.com/horizoncd/horizon/assets/100392073/ebc48512-6472-446e-a5d5-254ccf5b4066)
![image](https://github.com/horizoncd/horizon/assets/100392073/f9ce7f93-cdc4-4117-91bc-585ec8788506)
![image](https://github.com/horizoncd/horizon/assets/100392073/c832a634-4d02-49b6-be06-c8e691ae89dd)

**Comment by kilosonc** [comment]
hello @noovertime7 , Horizon routes traffic through Ingress. If you access Horizon-Web directly, the backend routing will not find the correct path. So you still need an ingress nginx controller, if you don't have it, you could try using horizon locally
https://horizoncd.github.io/docs/tutorials/how-to-install/local-installation

**Comment by kilosonc** [comment]
Further more, we invite you to talk with us in slack directly, https://join.slack.com/t/horizoncd/shared_invite/zt-1sehbmzcx-dgIwaExNR4fZKXppj5kmgQ.

**Comment by kilosonc** [comment]
@noovertime7 Besides, we suggest you upgrade horizon to the newest version by using `helm install` or `helm upgrade` with `--version` flag

**Comment by noovertime7** [comment]
Okay, I'll give it a try next week. Thank you for your reply
