### ISSUE TITLE
Who is using Horizon?

### ISSUE THREAD

**Issue by kilosonc** [horizoncd/horizon#191]
Who's using Horizon/谁在使用 Horizon?
The growth of the Horizon community is contingent upon the collaborative endeavors of each and every user and developer.
Horizon 社区的发展离不开每一位用户和开发者的共同努力。

The Horizon community appreciates every user and developer who uses and cares about Horizon. We strive to listen to each one of you to make the community more prosperous.
Horizon 社区感激每一位使用和关注 Horizon 的用户和开发者，我们努力倾听每一个人的声音，让社区变得更加繁荣。

So, the starting point for this topic is to encourage you, as a user or developer, to leave your real-world scenarios so that we can subsequently explore new and better solutions, schedule the releases, and solve real-world problems based on these scenarios!
所以，这个议题的出发点是希望作为用户或者开发者的您留下您的实际使用场景，以便我们后续基于此探索更好的解决方案，制定版本计划，解决实际问题。

We look forward to your comments in the comments space, including but not limited to the following areas.
我们期待您能在评论区留言，其内容包括但不限于以下方面。

Organization / 组织: e.g. NetEase Corp.
Region / 地区: e.g. Hangzhou, China
Contact / 联系方式: e.g. [zhoujinsong0505@163.com](mailto:zhoujinsong0505@163.com)
Usage Scenario / 使用场景: e.g., we use Horizon to automatically optimize Iceberg tables./ we use Horizon to build batch-and-stream-fused data pipelines.
Bests / 致敬,

Horizon Community

**Comment by kilosonc** [comment]
![20230829140046](https://github.com/horizoncd/horizon/assets/52988625/1c5e7ca4-9411-427e-ba1d-a98092bbe08f)
Organization / 组织: NetEase Cloud Music.
Region / 地区: Hangzhou, China
Contact / 联系方式: [Tom](mailto:hzsunjianliang@corp.netease.com)
Usage Scenario / 使用场景: Based on Horizon, Cloud Music has completed cloud-native transformation, with the majority of its applications running on the cloud. It supports feature such as canary release, HPA, Serverless, etc. For more information, please refer to https://zhuanlan.zhihu.com/p/616664314 & https://zhuanlan.zhihu.com/p/641095247

**Comment by caiqing0204** [comment]
Organization / 组织: 中税税务
Region / 地区: 北京
Contact / 联系方式: caiqing@zstax.com
Usage Scenario / 使用场景: 中台部门应用服务发布中心
