### ISSUE TITLE
helm install error?

### ISSUE THREAD

**Issue by justzx2011** [horizoncd/horizon#22]
helm install horizon horizon/horizon -n horizoncd --version 2.0.1 --create-namespace
coalesce.go:223: warning: destination for horizon.tektonci-resources.auth.dockerConfigJson is a table. Ignoring non-table value ({})
coalesce.go:223: warning: destination for horizon.tektonci-resources.auth.dockerConfigJson is a table. Ignoring non-table value ({})
Error: INSTALLATION FAILED: failed to install CRD crds/clustertriggerbindings-crd.yaml: resource mapping not found for name: "clustertriggerbindings.triggers.tekton.dev" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first

my k8s version is v1.25.6+k3s1

**Comment by yingliming** [comment]
helm install error 
coalesce.go:223: warning: destination for horizon.tektonci-resources.auth.dockerConfigJson is a table. Ignoring non-table value ({})
coalesce.go:223: warning: destination for horizon.tektonci-resources.auth.dockerConfigJson is a table. Ignoring non-table value ({})
Error: INSTALLATION FAILED: failed to install CRD crds/clustertriggerbindings-crd.yaml: resource mapping not found for name: "clustertriggerbindings.triggers.tekton.dev" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first

k8s v1.25.4

**Comment by kilosonc** [comment]
@iamyeka Help wanted

**Comment by iamyeka** [comment]
Please upgrade to 2.1.0 version of the Chart, steps are like below:
```
1. kubectl delete eventlisteners horizon-listener -nhorizon

2. helm uninstall horizon -nhorizoncd

3. k get crd | grep tekton | awk '{print $1}' | xargs kubectl delete crd

4. helm repo update horizon

5. helm install horizon horizon/horizon -n horizoncd --version 2.1.0 --create-namespace
```
