### ISSUE TITLE
horizon-mysql start error

### ISSUE THREAD

**Issue by justzx2011** [horizoncd/horizon#23]
my k8s version: v1.19.3+k3s3

k get pod -n horizoncd|grep mysql
horizon-mysql-0                                      0/1     Running            1          4m8s

mysql 07:53:30.24 INFO  ==> ** Starting MySQL setup **
mysql 07:53:30.88 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 07:53:31.06 INFO  ==> Initializing mysql database
mysql 07:53:31.75 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 07:53:31.77 INFO  ==> Using persisted data
mysql 07:53:32.64 INFO  ==> Running mysql_upgrade
mysql 07:53:32.85 INFO  ==> Starting mysql in background
mysql 07:56:02.74 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1061 (42000) at line 67 in file: '/docker-entrypoint-initdb.d/init.sql': Duplicate key name 'idx_application_id'
mysql 07:56:07.85 ERROR ==> Failed executing /docker-entrypoint-initdb.d/init.sql
mysql 07:56:08.34 INFO  ==> Stopping mysql

k get pod -n horizoncd|egrep -v "1/1|3/3|2/2"
NAME                                                 READY   STATUS             RESTARTS   AGE
horizon-mysql-0                                      0/1     Running            1          4m31s
horizon-job-57b588ffc6-8zpmf                         0/1     CrashLoopBackOff   4          117s
horizon-core-86f8f4c76f-xphr8                        0/1     CrashLoopBackOff   4          95s

 k logs horizon-core-86f8f4c76f-xphr8 -n horizoncd
2023/02/17 11:35:12 /horizon/lib/orm/orm.go:44
[error] failed to initialize database, got error dial tcp 10.43.164.121:3306: connect: connection refused

2023/02/17 11:35:12 /horizon/lib/orm/metrics.go:49 dial tcp 10.43.164.121:3306: connect: connection refused
[2.632ms] [rows:-] SHOW STATUS

2023/02/17 11:35:12 /horizon/lib/orm/metrics.go:52
[error] gorm:prometheus query error: dial tcp 10.43.164.121:3306: connect: connection refused
panic: dial tcp 10.43.164.121:3306: connect: connection refused

goroutine 1 [running]:
github.com/horizoncd/horizon/core/cmd.Run(0xc000974ab0)
	/horizon/core/cmd/cmd.go:267 +0x6525
main.main()
	/horizon/core/main.go:26 +0x2a

k logs horizon-job-57b588ffc6-8zpmf -n horizoncd

2023/02/17 11:34:56 /horizon/lib/orm/orm.go:44
[error] failed to initialize database, got error dial tcp 10.43.164.121:3306: connect: connection refused

2023/02/17 11:34:56 /horizon/lib/orm/metrics.go:49 dial tcp 10.43.164.121:3306: connect: connection refused
[1.812ms] [rows:-] SHOW STATUS

2023/02/17 11:34:56 /horizon/lib/orm/metrics.go:52
[error] gorm:prometheus query error: dial tcp 10.43.164.121:3306: connect: connection refused
panic: dial tcp 10.43.164.121:3306: connect: connection refused

goroutine 1 [running]:
github.com/horizoncd/horizon/job/cmd.Run(0xc000b86d40)
	/horizon/job/cmd/cmd.go:105 +0x15e5
main.main()
	/horizon/job/main.go:24 +0x2a

**Comment by kilosonc** [comment]
@iamyeka Could you handle this?

**Comment by iamyeka** [comment]
Maybe some trouble in k3s? I can't reproduce it on my local environment.
