### ISSUE TITLE
failed to deploy pipeline

### ISSUE THREAD

**Issue by stormzhai** [horizoncd/horizon#36]
Pipeline horizoncd/horizon-pipeline can't be Run; it has an invalid spec: invalid value: : finally.params[application].type, finally.params[clusterID].type, finally.params[cluster].type, finally.params[environment].type, finally.params[gitBranch].type, finally.params[gitCommit].type, finally.params[gitRepositoryUrl].type, finally.params[gitSubfolder].type, finally.params[gitTag].type, finally.params[imageURL].type, finally.params[pipelineJSONBlob].type, finally.params[pipelinerunID].type, finally.params[requestID].type, finally.params[token].type, tasks.params[application].type, tasks.params[clusterID].type, tasks.params[cluster].type, tasks.params[environment].type, tasks.params[gitBranch].type, tasks.params[gitCommit].type, tasks.params[gitRepositoryUrl].type, tasks.params[gitSubfolder].type, tasks.params[gitTag].type, tasks.params[imageURL].type, tasks.params[pipelineJSONBlob].type, tasks.params[pipelinerunID].type, tasks.params[requestID].type, tasks.params[token].type

**Comment by kilosonc** [comment]
More info about your environment wanted.

**Comment by iamyeka** [comment]
Please upgrade to 2.1.0 version of the Chart, steps are like below:
```
1. kubectl delete eventlisteners horizon-listener -nhorizon

2. helm uninstall horizon -nhorizoncd

3. k get crd | grep tekton | awk '{print $1}' | xargs kubectl delete crd

4. helm repo update horizon

5. helm install horizon horizon/horizon -n horizoncd --version 2.1.0 --create-namespace
```
