### ISSUE TITLE
no owners file? 

### ISSUE THREAD

**Issue by mouuii** [horizoncd/horizon#56]
**What would you like to be added**:
是否有owners 文件，方便知道谁对哪个模块比较清楚
**Why is this needed**:

**Comment by cubxxw** [comment]
As a review, I don't think that the use of owners in the early stage of the horizon will bring positive feedback, not the effect of `PR` efficiency.

We can use the plug-in to find the corresponding person in the code and send him an email or issue the issue.

We can also tag pron each commit message on github to identify where the last `PR` comes from.

You may find the steps in history and the code audit we need to cooperate with cicd actionsthrough tests and review

**FYI~**

**Comment by kilosonc** [comment]
Maybe later, not before we have enough people...
