### ISSUE TITLE
is tekton deploy task ambiguity？

### ISSUE THREAD

**Issue by mouuii** [horizoncd/horizon#63]
**What would you like to be added**:
in horizon system ci task deploy,we tell user "deploy success fully", is it better to be "notify cd success, start to deploy"?
**Why is this needed**:

**Comment by cubxxw** [comment]
Would it be better if we could notify the email?

**Comment by kilosonc** [comment]
Thanks for suggestions, the script in CI stage could be customized by system admin, it's not a problem if you want to get a more powerful ci stage.
