### ISSUE TITLE
request helm install support kubernetes 1.25+

### ISSUE THREAD

**Issue by flyhighzy** [horizoncd/horizon#73]
hello, we are using kubernetes 1.25.4 and want to try horizon, but we're blocked at first step: helm templates currently only support 1.19.3 ~ v1.24.7. Please help build a helm template for kubernetes v1.25+, thanks!

**Comment by iamyeka** [comment]
Kubernetes v1.25+ has removed PodSecurityPolicy, currently we're still using it. We may provide a switch to control whether to create PodSecurityPolicy. Let's see if that makes sense.

**Comment by kilosonc** [comment]
Hiiiii @flyhighzy, thanks for using Horizon! You can join Horizon slack, discuss it with us instantly https://join.slack.com/t/horizoncd/shared_invite/zt-1pqpobiwn-1mgV60SIa1oi4mL1WXf7uA

**Comment by kilosonc** [comment]
@flyhighzy now horizon chart has supported kubernetes v1.25+! https://github.com/horizoncd/helm-charts/releases/tag/horizon-2.1.11
