### ISSUE TITLE
could not install failed on aliyun or tencent cloud

### ISSUE THREAD

**Issue by kilosonc** [horizoncd/horizon#84]
The default storage class creates PVs that must be larger than 20GB, otherwise they cannot be created.

**Comment by LiuG-lynx** [comment]
The reason for this is that horzion deploys components with some pvc with pv <20Gi, and these PV sizes need to be set to 20Gi or larger,This is done by:

 **First method**
Download this min-pv-size-20Gi-values.yaml file locally
[min-pv-size-20Gi.values.yaml](https://github.com/horizoncd/helm-charts/blob/764376b6ce408d6701ea4fa75e08c84ac5b674e9/min-pv-size-20Gi-values.yaml)
```
helm install horizon horizon/horzion -n horzioncd --create-namespace -f min-pv-size-20Gi-values.yaml
```


**Second method** 
```bash 
helm pull horizon/horizon --untar && cd  horizon
# edit values.yaml
cp values.yaml min-pv-size-20Gi-values.yaml && vim min-pv-size-20Gi-values.yaml 
```

1. mysql.primary.persistence.size -> 20Gi
2. gitlab.persistence.size -> 20Gi
3. harbor.persistence.persistentVolumeClaim.databse.size -> 20Gi
4. harbor.persistence.persistentVolumeClaim.jobservice.size -> 20Gi

```
helm install horizon horizon/horzion -n horzioncd --create-namespace -f min-pv-size-20Gi-values.yaml
```
